// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Mon, 07 Dec 2020 06:43:44 EST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Ultralight bindings for golang
*/
package ultralight
